### ISSUE TITLE
I wish i could see more documentation

### ISSUE THREAD

**Issue by curtthemartian** [darconeous/xmas-color-effects#1]
I would love to see more documentation to understand what the different parts of your code do.  Thanks for publishing your amazing work! cudos to you!

**Comment by darconeous** [comment]
I'd be happy to add more comments to help make stuff more clear. What specific parts (Filenames and line numbers would be great) did you want more elaboration on?

**Comment by curtthemartian** [comment]
Unfortunatly right now I will have to get back to you in a few days.  
generally it would help me out to know what each file generally is meant to do.  That at least gives me something to go off of when attempting to understand the code.  I do not know what the github wiki section is about but that is an option aswell to explain things if it comes it that.  :-) Thankyou for sharing all your hard work!

**Comment by darconeous** [comment]
This project is being archived. Closing.
